// BOOKMARKS

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const EDIT_BOOKMARK = 'EDIT_BOOKMARK';
export const SET_BOOKMARKS = 'SET_BOOKMARKS';
export const ON_LOGOUT_SET_BOOKMARKS = 'ON_LOGOUT_SET_BOOKMARKS';


// FILTERS

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SHOW_USER_BOOKMARKS = 'SHOW_USER_BOOKMARKS';
export const SHOW_ALL_BOOKMARKS = 'SHOW_ALL_BOOKMARKS';
export const SHOW_PUBLIC_BOOKMARKS = 'SHOW_PUBLIC_BOOKMARKS';


// AUTH

export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
